###
GET http://localhost:8080/api/

###

POST http://localhost:8080/api/auth/signUp
content-type: application/json

{
  "name": "Ravik Ganguly",
  "email": "theravikganguly@gmail.com",
  "password": "12345678"
}

###

POST http://localhost:8080/api/auth/signIn
content-type: application/json

{
  "email": "pranabs1ngh@gmail.com",
  "password": "12345678"
}

###

GET http://localhost:8080/api/auth/signOut

###

POST http://localhost:8080/api/projects
content-type: application/json

{
  "name": "African Price"
}
 
###

PUT http://localhost:8080/api/projects/hgSGaQ9oU7dyz2dWAX5D
content-type: application/json

{
  "name": "Asap Task Manager",
  "memberIds": []
}

###

PUT http://localhost:8080/api/projects/hgSGaQ9oU7dyz2dWAX5D
content-type: application/json

{
  "name": "Updated Project",
  "extraField": "Yup throws error!"
}

###

DELETE http://localhost:8080/api/projects/hgSGaQ9oU7dyz2dWAX5D

###

POST http://localhost:8080/api/projects/hgSGaQ9oU7dyz2dWAX5D/lists
content-type: application/json

{
  "name": "Admin Bro Integration"
}
 
###

PUT http://localhost:8080/api/projects/hgSGaQ9oU7dyz2dWAX5D/lists/6KEi1MLduZA3J53oaIsE
content-type: application/json

{
  "name": "Remove Strapi",
  "extraField": "Yup throws error on extra fields!"
}

###

PUT http://localhost:8080/api/projects/hgSGaQ9oU7dyz2dWAX5D/lists/6KEi1MLduZA3J53oaIsE
content-type: application/json

{
  "name": "Remove Strapi"
}

###

DELETE  http://localhost:8080/api/projects/hgSGaQ9oU7dyz2dWAX5D/lists/6KEi1MLduZA3J53oaIsE