###
GET http://localhost:8080/api/

###

POST http://localhost:8080/api/auth/signUp
content-type: application/json

{
  "name": "Ravik Ganguly",
  "email": "theravikganguly@gmail.com",
  "password": "12345678"
}

###

POST http://localhost:8080/api/auth/signIn
content-type: application/json

{
  "email": "pranabs1ngh@gmail.com",
  "password": "12345678"
}

###

GET http://localhost:8080/api/auth/signOut

###

POST http://localhost:8080/api/projects
content-type: application/json

{
  "name": "African Price"
}
 
###

PUT http://localhost:8080/api/projects/5k0xXmPBp7mPQ9kE1jXO
content-type: application/json

{
  "name": "African Price Backend"
}

###

PUT http://localhost:8080/api/projects/0aDVY88OL7t4UWylQznS
content-type: application/json

{
  "name": "Updated Project",
  "extraField": "Yup throws error!"
}

###

DELETE http://localhost:8080/api/projects/0aDVY88OL7t4UWylQznS

###

POST http://localhost:8080/api/projects/0aDVY88OL7t4UWylQznS/lists
content-type: application/json

{
  "name": "Quivia Backend"
}
 
###

PUT http://localhost:8080/api/projects/0aDVY88OL7t4UWylQznS/lists/K7igSXV2wuJv00dPuX3J
content-type: application/json

{
  "name": "Updated Offline Quiz Games"
}

###

PUT http://localhost:8080/api/projects/hgSGaQ9oU7dyz2dWAX5D/lists/eE7UgUYgdgBQsynHK8CQ
content-type: application/json

{
  "name": "Add Backend",
  "extraField": "Yup throws error on extra fields!"
}

###

DELETE  http://localhost:8080/api/projects/0aDVY88OL7t4UWylQznS/lists/K7igSXV2wuJv00dPuX3J