###
GET http://localhost:8080/api/

###

POST http://localhost:8080/api/auth/signUp
content-type: application/json

{
  "name": "Tushar Maharana",
  "email": "tushar@gmail.com",
  "password": "12345678"
}

###

POST http://localhost:8080/api/auth/signIn
content-type: application/json

{
  "email": "tushar@gmail.com",
  "password": "12345678"
}

###

GET http://localhost:8080/api/auth/signOut

###

POST http://localhost:8080/api/projects
content-type: application/json

{
  "project": {
    "name": "New Project"
  }
}
 
###

PUT http://localhost:8080/api/projects/ZkKFeCq2IANnGJXL06wL
content-type: application/json

{
  "project": {
    "name": "Updated Project",
    "listIds": ["1"], 
    "memberIds": [],
    "extraField": "Yup throws error on extra fields!"
  }
}

###

PUT http://localhost:8080/api/projects/ZkKFeCq2IANnGJXL06wL
content-type: application/json

{
  "project": {
    "name": "Updated Project",
    "listIds": ["1", "2"], 
    "memberIds": []
  }
}

###

DELETE  http://localhost:8080/api/projects/xOQlWdISXztYNYJluhWB